### ISSUE TITLE
CRCON integration fails with "An unexpected error occurred!" Failed to ban player

### ISSUE THREAD

**Issue by richtea** [timraay/Barricade#20]
Hi, thanks for Barricade!

When I try to ban a player through the CRCON integration, I get a message as below:

![image](https://github.com/user-attachments/assets/0bcd11d6-0309-4b5d-afdf-546f05d87a88)

Are there any additional logs I can look at to maybe work out what's not working? I may have mucked things up as it was fairly painful to get the integration running (I initially tried on CRCON v10.1.x).

**Comment by timraay** [comment]
Have a look at the config of the reverse proxy you use for your CRCON installation and make sure websockets are being routed properly. It is trying to connect to `wss://admin1.yourdomain.com/ws/barricade` and getting status code 400 during the handshake.

**Comment by richtea** [comment]
That's fixed it, thanks! For anyone else using [Nginx Proxy Manager](https://nginxproxymanager.com/), you need to enable websockets _and_ HTTP/2 (this is configured on the **SSL** page for some reason).
