### ISSUE TITLE
CRCON integration always failing permission checks when not superuser

### ISSUE THREAD

**Issue by roland-jungwirth** [timraay/Barricade#9]
As per instructions I have set up a new admin user, and gave them "staff" permissions.
Then added ALL user permissions after getting the first "Token owner has insufficient permissions" message.
Created a new token for that user.

Added both API URL and token into the "add integration" on Discord. Got the "Token owner has insufficient permissions" message. Please explain exactly what the user needs.

**Comment by timraay** [comment]
Staff permissions are for user management. To give someone all permissions, you need to make them a superuser.

If a user is not a superuser, Barricade will look for the following permissions;
- api.can_view_blacklists (Can view available blacklists)
- api.can_create_blacklists (Can create blacklists)
- api.can_add_blacklist_records (Can add players to blacklists)
- api.can_change_blacklist_records (Can unblacklist players and edit blacklist records)
- api.can_delete_blacklist_records (Can delete blacklist records)

**Comment by roland-jungwirth** [comment]
![image](https://github.com/user-attachments/assets/cba746fc-1155-41ee-a0ca-b876f82c09a6)
Unfortunately not. These are the permissions that the user had, and I still got the same message. Even if I gave the user ALL permissions, barricade came back with the above error. Only giving the user "superuser status" resulted in the integration working.

**Comment by timraay** [comment]
Turns out there were some changes I'd missed when migrating CRCON APIs. Should be fixed now. Thanks!

**Comment by roland-jungwirth** [comment]
> Turns out there were some changes I'd missed when migrating CRCON APIs. Should be fixed now. Thanks!

Thank you for the fix!
